CREATE DATABASE MyWebDB;
GO

USE MyWebDB;
CREATE TABLE Users(UserID INT PRIMARY KEY IDENTITY, EmailAddress VARCHAR(50), FirstName VARCHAR(50), LastName VARCHAR(50));
CREATE TABLE Products(ProductID INT PRIMARY KEY IDENTITY, ProductName VARCHAR(50));
CREATE TABLE Downloads
(DownloadID INT PRIMARY KEY IDENTITY, 
UserID INT REFERENCES Users (UserID), 
DownloadDate SMALLDATETIME, 
FileName VARCHAR(50), 
ProductID INT REFERENCES Products (ProductID));



DROP DATABASE IF EXISTS MyWebDB;

SELECT * FROM MyWebDB;