CREATE DATABASE MyWebDB;
GO

USE MyWebDB;
CREATE TABLE Users(UserID INT IDENTITY NOT NULL PRIMARY KEY, EmailAddress VARCHAR(50), FirstName VARCHAR(50), LastName VARCHAR(50));
CREATE TABLE Products(ProductID INT IDENTITY PRIMARY KEY NOT NULL, ProductName VARCHAR(50));
CREATE TABLE Downloads
(DownloadID INT IDENTITY PRIMARY KEY NOT NULL, 
UserID INT REFERENCES Users (UserID), 
DownloadDate SMALLDATETIME, 
FileName VARCHAR(50), 
ProductID INT REFERENCES Products (ProductID));

